//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
