//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTS_SERVICECONFIG
    {
        public long SERVICEID { get; set; }
        public string SERVICENAME { get; set; }
        public string SERVICEDISPLAYNAME { get; set; }
        public string SERVICEDESCRIPTION { get; set; }
        public string SERVICEINVOKETYPE { get; set; }
        public string DLLNAME { get; set; }
        public string SERVICEPARAMS { get; set; }
        public string TIME { get; set; }
        public Nullable<short> RETRYCOUNT { get; set; }
        public Nullable<short> MAXERRORS { get; set; }
        public Nullable<byte> STATUS { get; set; }
    }
}
