//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTS_WORK_GROUP_MAPPING
    {
        public int ID { get; set; }
        public int WORKCODEACTIVITYID { get; set; }
        public int GROUP_ID { get; set; }
    
        public virtual MTS_GROUPS MTS_GROUPS { get; set; }
        public virtual WorkCodesActivity WorkCodesActivity { get; set; }
    }
}
