//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTS_SMTPDETAILS
    {
        public long SmtpID { get; set; }
        public string SmtpName { get; set; }
        public string SmtpClientHost { get; set; }
        public int SmtpClientPort { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public string Domain { get; set; }
        public bool EnableSsl { get; set; }
        public int TimeOut { get; set; }
        public byte SmtpDeliveryMethod { get; set; }
        public bool UseDefaultCredentials { get; set; }
    }
}
