//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTS_EMAILSCHEDULE
    {
        public long SCHEDULEID { get; set; }
        public long TEMPLATEID { get; set; }
        public string SCHEDULEDESCRIPTION { get; set; }
        public string SENDBY { get; set; }
        public string DAY { get; set; }
        public Nullable<System.TimeSpan> TIME { get; set; }
    }
}
