//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int WorkCodeActivityId { get; set; }
        public int ProjectId { get; set; }
        public int EmployeeId { get; set; }
        public string Description { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public string workCodeActivity { get; set; }
        public int WorkCodeActivityId { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
        public virtual WorkCodesActivity WorkCodesActivity { get; set; }
    }
}
