//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int WeeklyReportId { get; set; }
    
        public virtual WeeklyReport WeeklyReport { get; set; }
    }
}
